'use client';
import { ArrowLeft, Bot, SendHorizontal } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import { BottomNav } from '@/components/layout/BottomNav';
import { Footer } from '@/components/layout/Footer';

type Msg={role:'u'|'ai';text:string;time:string};
export default function Chat(){
  const [lang,setLang]=useState('EN');const [text,setText]=useState('');const [msgs,setMsgs]=useState<Msg[]>([]);
  const send=async(message=text)=>{if(!message.trim())return;const hist: Msg[]=[...msgs,{role:'u',text:message,time:new Date().toLocaleTimeString()}];setMsgs(hist);setText('');const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,history:hist,language:lang})});const d=await res.json();setMsgs(v=>[...v,{role:'ai',text:d.reply,time:new Date().toLocaleTimeString()}]);};
  return <div className='app-phone p-4 pb-20'><div className='flex items-center justify-between'><Link href='/dashboard' className='flex items-center gap-2'><ArrowLeft size={16}/><Bot className='text-[#00D4FF]'/><div><p className='font-semibold'>VitalPulse AI</p><p className='text-[11px] text-soft'>Ask anything about your family member</p></div></Link><div className='flex gap-1 text-xs'>{['EN','বাংলা','हिंदी'].map(l=><button key={l} onClick={()=>setLang(l)} className={`px-2 py-1 rounded-full ${lang===l?'bg-[#00D4FF] text-[#071016]':'panel'}`}>{l}</button>)}</div></div><div className='panel mt-3 p-2 text-xs'>Ramesh Kumar · stable · HR 88 · SpO₂ 97%</div><div className='mt-3 h-[54vh] overflow-y-auto space-y-2'>{msgs.length===0?<div className='panel grid place-items-center p-8 text-center'><Bot className='mb-2 text-[#00D4FF]'/><p>Hello. I am VitalPulse AI.</p><p className='text-soft text-sm'>Ask me anything or paste medical report text.</p><div className='mt-3 flex flex-wrap justify-center gap-2'>{['Is everything okay?','What do these vitals mean?','Should I be worried?'].map(q=><button key={q} onClick={()=>void send(q)} className='rounded-full border border-cyan-400/40 px-3 py-1 text-xs'>{q}</button>)}</div></div>:msgs.map((m,i)=><div key={i} className={m.role==='ai'?'panel border-l-2 border-l-[#00D4FF] p-2 text-sm':'ml-10 rounded-xl bg-cyan-400/20 p-2 text-sm'}>{m.text}<p className='text-[10px] text-soft mt-1'>{m.time}</p></div>)}</div><div className='mt-2 flex gap-2'><button onClick={()=>setText('Paste blood report values here for explanation...')} className='rounded-xl border border-cyan-400/40 px-2 text-xs'>📎 Paste Report</button><input value={text} onChange={e=>setText(e.target.value)} placeholder='Ask anything or paste a report...' className='flex-1 rounded-xl border border-cyan-400/30 bg-[#071016] p-3 text-sm'/><button onClick={()=>void send()} className='rounded-xl bg-[#00D4FF] px-3 text-[#071016]'><SendHorizontal size={16}/></button></div><Footer/><BottomNav active='chat'/></div>
}
